import logging
from typing import Optional, Dict, Any, List
from django.utils import timezone
from apps.assistant.models import ChatConversation, ChatMessage
from .pubmed_service import pubmed_service
from .llm_provider import get_llm_provider

logger = logging.getLogger(__name__)

MANDATORY_REGULATORY_DISCLAIMER = (
    "This synthesized medical explanation is generated by an automated AI clinical assistant "
    "for educational and triage guidance only. It does not substitute for formal clinical evaluation, "
    "diagnosis, or personalized prescription by a licensed healthcare provider."
)


class RAGAssistantEngine:
    """
    Retrieval-Augmented Generation (RAG) engine for clinical decision support.
    Synthesizes evidence-based clinical explanations grounded in PubMed literature
    and patient clinical records using pluggable LLM architecture.
    """

    def _normalize_query(self, query: str) -> str:
        """Normalizes clinical query by trimming whitespace and punctuation noise."""
        clean = " ".join(query.strip().split())
        return clean

    def _build_patient_context(self, patient_user) -> str:
        """Assembles localized patient context (medications, records) if available."""
        if not patient_user:
            return ""

        context_parts = []
        try:
            from apps.medicines.models import Medication
            from apps.medical_records.models import LabReport

            active_meds = Medication.objects.filter(patient=patient_user, is_active=True).values_list("name", flat=True)[:5]
            if active_meds:
                context_parts.append(f"Active Medications: {', '.join(active_meds)}.")

            recent_labs = LabReport.objects.filter(patient=patient_user).values_list("title", flat=True)[:3]
            if recent_labs:
                context_parts.append(f"Recent Lab Records: {', '.join(recent_labs)}.")
        except Exception as e:
            logger.warning("Could not assemble patient context: %s", e)

        return " ".join(context_parts)

    def process_chat(
        self,
        user,
        prompt: str,
        patient_user=None,
        conversation_id: Optional[int] = None,
        limit_citations: int = 3,
    ) -> Dict[str, Any]:
        """
        Executes end-to-end RAG pipeline:
        1. Manages chat conversation session.
        2. Query normalization.
        3. Retrieves PubMed citations and abstracts.
        4. Synthesizes clinical answer via LLM provider.
        5. Persists user and assistant messages with citations.
        6. Returns structured payload with mandatory regulatory disclaimer.
        """
        clean_prompt = self._normalize_query(prompt)

        # 1. Session management
        conversation = None
        if conversation_id:
            conversation = ChatConversation.objects.filter(id=conversation_id, user=user).first()

        if not conversation:
            title = clean_prompt[:60] + "..." if len(clean_prompt) > 60 else clean_prompt
            conversation = ChatConversation.objects.create(user=user, title=title)

        # 2. Record user message
        ChatMessage.objects.create(
            conversation=conversation,
            role="user",
            content=clean_prompt,
            sources=[],
        )

        # 3. Retrieve PubMed evidence
        pubmed_res = pubmed_service.search_pubmed(clean_prompt, limit=limit_citations, fetch_abstracts=True)
        citations = pubmed_res.get("citations", [])

        # 4. Synthesize answer with context using LLM provider
        patient_context = self._build_patient_context(patient_user)
        llm_provider = get_llm_provider()
        llm_result = llm_provider.generate_response(clean_prompt, citations, patient_context)
        response_text = llm_result.get("response", "")

        # 5. Record assistant response with citations
        assistant_msg = ChatMessage.objects.create(
            conversation=conversation,
            role="assistant",
            content=response_text,
            sources=citations,
        )

        # Update conversation timestamp
        conversation.save(update_fields=["updated_at"])

        return {
            "conversation_id": conversation.id,
            "message_id": assistant_msg.id,
            "query": clean_prompt,
            "response": response_text,
            "citations": citations,
            "disclaimer": MANDATORY_REGULATORY_DISCLAIMER,
            "patient_context_applied": bool(patient_context),
            "provider": llm_result.get("provider", "extractive"),
            "model": llm_result.get("model", "grounded_rules"),
            "grounded": llm_result.get("grounded", bool(citations)),
            "created_at": assistant_msg.created_at,
        }


rag_assistant_engine = RAGAssistantEngine()

