# Generated by Django 5.2.17 on 2026-09-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
